version: '3.9'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: wine
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  app:
    image: app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
  
volumes:
    mysql-data:
        driver: local      
